#!/usr/bin/env sh
set -eu

# Scoped, host-isolated Claude config dir for the sandbox (mounted into the
# backend). Create it up front so Docker doesn't create it root-owned.
mkdir -p "${HOME}/.claude-sandbox"

# Optional git-push SSH key dir (ships in the repo as ssh/.gitkeep, mounts into
# the container at ~/.ssh). Tighten perms for OpenSSH — git clones dirs 0755 and
# SSH refuses a group/world-accessible key dir. Empty is fine; SSH is optional.
mkdir -p ssh && chmod 700 ssh

# Optional GPU: if the host has a DRM render node, generate a compose override
# that passes the first one into the sessions container, so GUI tests get real
# hardware GL instead of llvmpipe. Kept in an override (gitignored, only written
# when absent) so the committed compose file stays portable — a host with no GPU
# simply has no override and nothing fails. Delete the file to opt out.
if [ ! -f docker-compose.override.yml ]; then
    node=$(ls /dev/dri/renderD* 2>/dev/null | head -1 || true)
    if [ -n "${node:-}" ]; then
        cat > docker-compose.override.yml <<YAML
# Auto-generated by generate-env.sh (gitignored). Passes the host's DRM render
# node into sessions for hardware-accelerated GL in GUI tests. Safe to delete.
services:
  sessions:
    devices:
      - ${node}:${node}
YAML
        echo "docker-compose.override.yml created (GPU render node ${node})"
    fi
fi

# Seed the (gitignored) container settings from the example on first run.
# docker-compose bind-mounts this file (read-write — the in-dashboard settings
# editor persists edits to it), so it must exist before `up`/`build`.
# Done before the .env early-exit so it still seeds on later runs if deleted.
if [ ! -f container-settings.json ]; then
    cp container-settings.example.json container-settings.json
    echo "container-settings.json created from container-settings.example.json"
fi

if [ -f .env ]; then
    echo ".env already exists, skipping (delete it first to regenerate)"
    exit 0
fi

cp .env.example .env
sed -i "s/^UID=.*/UID=$(id -u)/" .env
sed -i "s/^GID=.*/GID=$(id -g)/" .env

echo ".env created with UID=$(id -u) and GID=$(id -g)"
